### ISSUE TITLE
Add Support for the Function Calling API for OpenAI Models

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziLLM#10]
### Problem

Some conversations require additional context that can be provided to a an LLM to provide additional context to the conversation.

### Solution

We can use the [function calling API](https://platform.openai.com/docs/guides/gpt/function-calling) in the OpenAI interface to enable a structured interaction with the LLM to request additional data and provide it back to the conversation flow.

### Additional context

Feel free to use this discussion to discuss the API of the functionality and how to easily integrate that functionality in SpeziML

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
The related API in the OpenAI modules has been merged and released with the latest version: https://github.com/MacPaw/OpenAI/pull/78

**Comment by philippzagar** [comment]
#42 introduced a simple-to-use DSL for handling OpenAI function calls.
