### ISSUE TITLE
Edit ChatView/Message UI

### ISSUE THREAD

**Issue by dguo8412** [StanfordSpezi/SpeziLLM#14]
### Problem

For multiline user input messages, the second subsequent lines are aligned to the right instead of the left. See the image below for reference.
![IMG_6583](https://github.com/StanfordSpezi/SpeziML/assets/46211285/17f41e01-4dcf-4bba-b4c7-812f0cf604d0)

### Solution

Edit the chat UI to make multiline chats align to the left.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@dguo8412 Thank you for posting the issue. The best way to tackle this would be to remove this property here and just use the same alignment for both `Chat` alignments: https://github.com/StanfordSpezi/SpeziML/blob/main/Sources/SpeziOpenAI/MessageView.swift#L27

**Comment by philippzagar** [comment]
Resolved by https://github.com/StanfordSpezi/SpeziChat/pull/10

**Comment by philippzagar** [comment]
Resolved by https://github.com/StanfordSpezi/SpeziChat/pull/10
