### ISSUE TITLE
Add `Binding<Bool>` to the `ChatView` to Display a "Three Dot Typing" Indicator

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziLLM#15]
### Problem

It would be great to demonstrate progress to the user when they have sent a message to the LLM and the LLM started processing without already providing a first word. This is commonly indicated using a three dot typing indicator.

### Solution

The `ChatView` view should get an optional `Bool` `Binding` that can be used to control the display of a typing indicator.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
A three-dot typing indicator is introduced by StanfordSpezi/SpeziChat#6
