### ISSUE TITLE
Abstract the `ChatView` into a Separate Swift Package Target

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziLLM#16]
### Problem

The `ChatView` and related views should not be as closely bundled to the OpenAI module. They should be hosted in a separate target.

### Solution

The current types like `Chat` and other elements from the OpenAI dependency should replaced with protocols that abstract the concrete implementations to the using module.
We should consider better names then `Chat` for an individual message.

The new module should then be used in then OpenAI module to enable a chat interface.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
How does everyone feel about the `ChatView` moving to the [SpeziViews](https://github.com/StanfordSpezi/SpeziViews) module?

**Comment by philippzagar** [comment]
This is done via `SpeziChat`: https://github.com/StanfordSpezi/SpeziChat
