### ISSUE TITLE
Create an `OpenAIChatView`

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziLLM#17]
### Problem

A common use case of the SpeziML module is to create a chat interface with a LLM model that is initialized with a first conversation (instance of `[Chat]` while `Chat` is not the best name as noted in #16).

From there on, the user can respond to the messages and the whole interaction is handle by the LLM-specific component. For the OpenAI use case this would be the `OpenAIComponent`.

### Solution

It would be good to create an `OpenAIChatView` that abstract the functionality into a dedicated `View` while enabling access to the `[Chat]` instance and the other bindings (e.g., also introduced ones in #15) if the developer wants to.

The [`InspectResourceChat`](https://github.com/StanfordBDHG/LLMonFHIR/blob/main/LLMonFHIR/FHIR%20Display/InspectResourceChat.swift) view in the [LLMonFHIR](https://github.com/StanfordBDHG/LLMonFHIR) already provides a nearly complete implementation of the feature. 

It would be good for the view to support the functionality of creating the initial prompt (`[Chat]`) instance using an environment object and maybe even allow an async initialization providing a default message if the `[Chat]` instance is completely empty.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
Done in: https://github.com/StanfordSpezi/SpeziLLM/blob/main/Sources/SpeziLLM/Views/LLMChatView.swift
