### ISSUE TITLE
Native visionOS Support

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziLLM#25]
### Problem

With a few projects using visionOS and testing on the Apple Vision Pro, we want to move all Spezi modules in the Stanford Spezi organization to adopt the native UI components of visionOS.

### Solution

Update all UI components to use native SwiftUI components on visionOS. We also need visionOS as a supported platform for the Swift package file, and we may update the Swift tools version to 5.9.

You can learn more about visionOS and SwiftUI for visionOS at https://developer.apple.com/visionos/learn/.

All UI changes should be as cross-platform as possible. Increasing the iOS minimum platform target is acceptable.

Feel free to use comments under this issue to discuss the best way to approach the adoption of visionOS for the Spezi module.

### Additional context

It is required to install the latest [Xcode 15 beta](https://developer.apple.com/xcode/) to address this issue.

Unfortunately, UI tests are currently not supported for visionOS.
The [StanfordBDHG/SwiftPackageTemplate](https://github.com/StanfordBDHG/SwiftPackageTemplate) demonstrates [the CI setup for visionOS](https://github.com/StanfordBDHG/SwiftPackageTemplate/blob/main/.github/workflows/build-and-test.yml#L33) that should also be adopted for this Spezi module.

This change will be considered a breaking change.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
Addressed by: https://github.com/StanfordSpezi/SpeziLLM/pull/47
