### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by pedrodotavila** [StanfordSpezi/SpeziLLM#67]
### Use Case

This works pretty nice in iOS, when you guys are planning to do that same in Android?

### Problem

To get parity in an implementation, not having an Android version it wouldn't be possible

### Solution

Having an Android version makes it completely solved

### Alternatives considered

there are not alternatives.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
We're working on an Android version of the framework, stay tuned! You can see our progress at the repository here: https://github.com/StanfordSpezi/SpeziKt
