### ISSUE TITLE
The test app cannot be run 

### ISSUE THREAD

**Issue by luionTW** [StanfordSpezi/SpeziLLM#76]
### Description

/Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/UITests-brggdwcrjsospgbzlyoajdgmympf/SourcePackages/checkouts/SpeziViews/Sources/SpeziViews/Views/Layout/HorizontalGeometryReader.swift:42:22 Main actor-isolated property 'width' can not be mutated from a Sendable closure

Please fix the bug for from SpeziViews repo.

### Reproduction

Just tap Xcode build

### Expected behavior

no error found during the build.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by luionTW** [comment]
Hi @PSchmiedmayer , 

Thanks the information.

I noticed that the Xcode version in GitHub Actions is 16.0.1, while I am using Xcode 16.2 beta and an iPhone 15 Pro. I am not sure if this is the root cause.

**Comment by PSchmiedmayer** [comment]
Thank you for the additional context; it might be that the Xcode 16.2 beta could have changed some Swift behavior; can you try to reproduce the error in Spezi Views and see if there is a quick fix for the underlying issue? 

Happy to see a PR that fixes this in time for Xcode 16.2 to be released 👍

**Comment by luionTW** [comment]
Hi @PSchmiedmayer,

Here are the steps to reproduce the issue in the SpeziView repo:
- Open the Tests project in Xcode 16.2 beta and compile it.
- The error will be triggered immediately.

I am working on a fix, but it causes multiple dependency errors. Thank you.

Capture of 'state' with non-sendable type 'ValidationState.Binding' in a `@Sendable` closure

![image](https://github.com/user-attachments/assets/5a43f1ee-e4d6-4621-8e78-a698cb94ef51)

**Comment by philippzagar** [comment]
@bryan1anderson Closing out the issue as a fix was merged in StanfordSpezi/SpeziViews#48
