### ISSUE TITLE
Value of type 'ModelConfiguration' has no member 'prepare'

### ISSUE THREAD

**Issue by bryan1anderson** [StanfordSpezi/SpeziLLM#77]
### Problem

Value of type 'ModelConfiguration' has no member 'prepare'
`let prompt = modelConfiguration.prepare(prompt: formattedChat)`

### Solution

Fix it so that it compiles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Thank you @bryan1anderson! Thank you for making the contribution and let us know how you are using the package for your project. We always welcome contributions and improvements; let us know if you are interested in contributing beyond this PR 👍

**Comment by philippzagar** [comment]
Bug fixed in: https://github.com/StanfordSpezi/SpeziLLM/pull/80
