### ISSUE TITLE
Bug report: LLMLocal does not work in TestApp

### ISSUE THREAD

**Issue by joshgalvan** [StanfordSpezi/SpeziLLM#82]
### Description

When trying to use LLMLocal within the test app, it crashes.

### Reproduction

Cloning the project, running the TestApp on a real device, and tapping 'LLMLocal' causes a crash

### Expected behavior

The download functionality would be presented and the rest of the test flow would be available.

### Additional context

The error presented says it expects `LLMLocalPlatform()` to be present in the `LLMRunner`. Adding `LLMLocalPlatform()` to the runner does cause the download view to present, but the downloaded model never runs saying it never gets initialized. I am sure I have enough memory as I am running the app on a 64GB M3 Max.

[This](https://github.com/breakingwave/SpeziLLM) fork of this repo does work, however.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
@LeonNissen made some changes to the Local execution platform that were merged recently, so I'll defer to him!

**Comment by LeonNissen** [comment]
Hi @joshgalvan, thanks for this bug report! What version are you using? And will the model finish downloading, or does it crash before?

**Comment by joshgalvan** [comment]
Hello! This bug was produced in the current version, 0.9.0. The model will download but produces an error upon trying to inference saying something along the lines: "The model is not initialized. Please try closing and reopening the app", where closing and reopening never works.

**Comment by LeonNissen** [comment]
OK, thanks! Yes, you would need to include the `LLMLocalPlatform` in the `LLMRunner` in order to execute local models, so this should be correct. However, during the download, the model should not be initialized (only after the download has successfully finished as of version 0.9.0 – this will be fixed with #81). Also, the error message ("The model is not initialized. Please try closing and reopening the app") is not from SpeziLLM. 
Do you mind sharing more code? Otherwise, you can have a look in the UITests project (https://github.com/StanfordSpezi/SpeziLLM/tree/main/Tests/UITests) on how to use the new API. 
Maybe this could be a mismatch between dependencies...

**Comment by joshgalvan** [comment]
Sorry, my recollection of the error was wrong. I just freshly cloned the repo and have found that the actual error is:
![Screenshot 2024-12-17 at 5 45 38 PM](https://github.com/user-attachments/assets/a86fcd3d-4c4c-40a1-b645-7622f220194c)
This appears after adding `LLMLocalPlatform()`, downloading the model, and entering a message into the chat view and pressing `enter`.

My main point is not really about how to use the API, it's that the test app should work upon cloning. It is expected that I would open the test app, navigate to LocalLLM, download an LLM, and then be able to use it within the test app.

**Comment by joshgalvan** [comment]
Trying it on my iPad I actually get this as an alert:
```
LLM not ready yet.

The LLM needs to be initialized before usage.

Make sure the application initialized the LLM properly. Try restarting the application.
```

Maybe I did remember it correctly. The "LLM file not found" is probably from something else related to me deleting the app's data and rebuilding it various times.

**Comment by LeonNissen** [comment]
> My main point is not really about how to use the API, it's that the test app should work upon cloning. It is expected that I would open the test app, navigate to LocalLLM, download an LLM, and then be able to use it within the test app.

Yes you're totally right! This should work out of the box!

I think I just found one issue that could solve your problem.
The test app [downloads the `phi3_4bit` model](https://github.com/StanfordSpezi/SpeziLLM/blob/fd9f1cacb19199576656db4c4dd0c81923b3597a/Tests/UITests/TestApp/LLMLocal/Onboarding/LLMLocalOnboardingDownloadView.swift#L22), however, later on we try to initialize the [using `llama3_8B_4bit`](https://github.com/StanfordSpezi/SpeziLLM/blob/main/Tests/UITests/TestApp/LLMLocal/LLMLocalChatTestView.swift#L28).

Can you just try out setting both models to the same?

**Comment by joshgalvan** [comment]
Yep, that works!

**Comment by LeonNissen** [comment]
Awesome! Many thanks again for this bug report, we will adjust that in the next PR 👍
